version: "3.6"

services:
  jogoteca:
    depends_on:
      - mysql
    image: dansolo7/jogoteca:2.0
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    ports:
      - "8080:80"
    networks:
      - backend
    container_name: jogoteca

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    ports:
    - 3306:3306
    networks:
      - backend
    container_name: mysql
    command: [--default-authentication-plugin=mysql_native_password]

networks:
  backend: # Overlay
